version: '3.0'

services:
  dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - ${DYNAMODB_PORT}:${DYNAMODB_PORT}
    volumes:
      - ~/dynamodb-data:/data
    env_file: .env

  database:
    image: 'postgres:latest'
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ~/pg-data/:/var/lib/postgresql/data/
    env_file: .env

  test_database:
    image: 'postgres:latest'
    ports:
      - ${DATABASE_TEST_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file: .env.test
